language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

before_script: composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/coveralls -v; fi
